### ISSUE TITLE
Change default MTU back to 1500 for eth/usb/pan/wifi from 9000

### ISSUE THREAD

**Issue by joshschmelzle** [WLAN-Pi/pi-gen#36]
There is an issue where various interfaces including eth0, usb0, pan0, & wlan0 are defaulting to an MTU of 9000. This affects performance testing when intermediary network devices have a lower MTU.

**Comment by joshschmelzle** [comment]
Example of the mtu being applied to eth0, pan0, usb0, wlan0 by default on the v3.1.0 image.

```bash
wlanpi@wlanpi-087:~ $ ifconfig | grep mtu
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 9000
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
pan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 9000
usb0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 9000
wlan0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 9000
```

**Comment by jiribrejcha** [comment]
Removed kernel patch which enabled MTU up to 9000 B:
https://github.com/WLAN-Pi/wlanpi-kernel/commit/eb626d4ca19ca278509c69aac4f0f6074cf907a1

Built a new kernel package, which only allows MTU up to 1500 B (Linux default):
https://github.com/WLAN-Pi/wlanpi-kernel/actions/runs/3203562559

```
wlanpi@wlanpi-88e:~ $ sudo ip link set mtu 1500 dev eth0
wlanpi@wlanpi-88e:~ $ sudo ip link set mtu 1501 dev eth0
Error: mtu greater than device maximum.

```
Current kernel:
`Linux wlanpi-6dc 5.19.14-v8-wlanpi+ #1 SMP PREEMPT Fri Oct 7 09:09:24 UTC 2022 aarch64 GNU/Linux
`
Current MTU on interfaces:
```
wlanpi@wlanpi-88e:~ $ ifconfig | grep mtu
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST> mtu 1500
lo: flags=73<UP,LOOPBACK,RUNNING> mtu 65536
pan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST> mtu 1500
wlan0: flags=4099<UP,BROADCAST,MULTICAST> mtu 1500
```

If MTU 9000 B is needed in future, we can revisit that after we migrate to networkd.
