### ISSUE TITLE
Bundle sntp for NTP client testing

### ISSUE THREAD

**Issue by crvallance** [WLAN-Pi/pi-gen#42]
Sometimes it is valuable to be able to query an NTP server to determine if it is truly serving NTP and/or there is no firewall blocking your path. Including a tool/package that can do this could be helpful for those needing to troubleshoot their network.

@jiribrejcha has suggested [sntp](https://linux.die.net/man/8/sntp)

I have previously used a pure python script leveraging sockets to accomplish a similar task.

**Comment by jiribrejcha** [comment]
Done in https://github.com/WLAN-Pi/pi-gen/commit/3a0e05e87bf52c8fdcefd5c2d32fd60cb2914cb0
