### ISSUE TITLE
Bug: Not detecting all broadcasting APs

### ISSUE THREAD

**Issue by Coder84619** [WLAN-Pi/pi-gen#50]
I'm using an M1 Pro Macbook Pro with WiFi explorer Pro 3.6.3. When using my WLAN Pi R4 as a sensor it correctly detects 3 APs for my 5GHz and 6 GHz BSSIDs. However, for the 2.4 GHz SSIDs WiFi explorer is only showing 2 BSSIDs. If I disconnect the WLAN Pi R4 and just use the Mac's native WiFi all 3 2.4 GHz BSSIDs appear. This also briefly happened on the 6 GHz band, but cleared up.

**Comment by jiribrejcha** [comment]
1. What Wi-Fi adapter are you using?

2. What regulatory domain?

3. What WLAN Pi OS release?

4. How strong is the RSSI for the undetected 2.4 GHz BSSID?

**Comment by Coder84619** [comment]
1) COMFRST AX1800 (came with the WLAN Pi R4 kit)
2) US
3) 3.2.0
4) -69

**Comment by jiribrejcha** [comment]
That potentially sounds like a MediaTek firmware issue we have fixed recently fixed.

Please check for latest package versions and update this package for me:
`sudo apt update && sudo apt install wlanpi-misc-firmware -y`

**Comment by Coder84619** [comment]
Didn't help. It's missing 2x 2.4 GHz BSSID, and for a while two 6 GHz BSSIDs. All BSSIDs appear on my M3 MacBook Air. Interestingly, all 3 5 GHz BSSIDs ARE listed. All the 6 GHz BSSIDs were slow to come up, but eventually did make it. Not so lucky for 2.4 GHz.

**Comment by jiribrejcha** [comment]
Did you reboot after upgrading the firmware package?

Can you please take an over the air packet capture on the WLAN Pi on one of the 2.4 GHz channels where the missing AP is present? 5 second length is fine. Feel free to e-mail me jirka@jiribrejcha.net if you don't want to share the PCAP publicly.

**Comment by Coder84619** [comment]
Yes I did a full reboot, and also sudo apt-get upgrade -y, then another reboot. Probably have to wait until this weekend to figure out how to do a capture.

**Comment by Coder84619** [comment]
@jiribrejcha I emailed you a pcap.

**Comment by Coder84619** [comment]
Any update on this? It's still happening.

**Comment by joshschmelzle** [comment]
@Coder84619 did you try the latest version of WFE? What channels are your 6 GHz APs on?
