### ISSUE TITLE
wiperf deprecated?

### ISSUE THREAD

**Issue by nimbo78** [WLAN-Pi/pi-gen#51]
trying to install new wlanpi (without display) but seems like no wiperf from the box. is it deprecated package?

**Comment by jiribrejcha** [comment]
Yes, it is no longer being maintained. 

Nigel has done an amazing job at writing wiperf. If you are interested in developing it further and maintaining it yourself, [reach out to Nigel](http://wifinigel.blogspot.com/p/contact.html?m=1), please. We will be happy to consider adding it back in.
